# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 2 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter:
markdown: kramdown
disqus:
google_analytics: #fernandascovino
title: fernandascovino

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title:

description: Stylish Jekyll Theme
author:
  name: fernandascovino
  email: fscovinom@gmail.com
  github: fernandascovino
  twitter: fernandascovino
  pinterest: 
  linkedin: fernanda-scovino
  bio: <br>Passionate for data & viz for social good <br> • <br>Data Sientist <a href="http://www.rio.rj.gov.br/web/smac">@SMAC-Rio</a> <br>Co-founder <a href="https://basedosdados.org">@basedosdados</a> <br>Former <a href="https://www.impulsogov.com.br/">@ImpulsoGov</a>, <a href="https://direitorio.fgv.br/cts">@CTSFGV</a> <br>Bsc Applied Math @ FGV-Rio
  email_md5:
  photo: /images/myself.png

categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
