# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter:
markdown: kramdown
disqus: fernandascovino
google_analytics: #fernandascovino
title: fernandascovino

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title:

description: Stylish Jekyll Theme
author:
  name: fernandascovino
  email: fscovinom@gmail.com
  github: fernandascovino
  twitter: fernandascovino
  pinterest: 
  linkedin: fernandascovino
  bio: <br>Passionate for data & viz for social good <br> • <br>Data Research @ CEIPE-FGV <br>Applied Math @ FGV-Rio
  email_md5:

categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
